name: assets_scanner_plus
description: assets_scanner_plus helps you generate assets path constants to r.dart file, you can preview the images assets by hovering over the constants.
version: 3.0.0
homepage: https://github.com/amorenew/assets_scanner_plus

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  build: ^3.0.0
  path: ^1.9.1
  glob: ^2.1.3
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.26.2
  build_test: ^3.3.0
