name: assets_scanner_plus
description: assets_scanner_plus helps you generate assets path constants to r.dart file, you can preview the images assets by hovering over the constants.
version: 2.0.0
homepage: https://github.com/amorenew/assets_scanner_plus

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  build: ^2.4.1
  path: ^1.9.0
  glob: ^2.1.2
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.7
  build_test: ^2.2.2
