import 'dart:async';
import 'dart:io';

import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

class _AssetsScannerOptions {
  const _AssetsScannerOptions._({
    this.path = 'lib',
    this.className = 'R',
    this.ignoreComment = false,
  });

  factory _AssetsScannerOptions() => const _AssetsScannerOptions._();

  factory _AssetsScannerOptions.fromYamlMap(YamlMap map) {
    return _AssetsScannerOptions._(
      path: map['path'] as String? ?? 'lib',
      className: map['className'] as String? ?? 'R',
      ignoreComment: map['ignoreComment'] as bool? ?? false,
    );
  }

  /// The path where the `r.dart` file locate. Note that the `path` should be
  /// sub-path of `lib/`.
  final String path;

  /// The class name of the `r.dart`.
  final String className;

  /// Indicate the comments need to be generated or not. Note that the you can't
  /// preview the images assets if `ignoreComment` is `true`.
  final bool ignoreComment;

  @override
  String toString() =>
      '_AssetsScannerOptions(path: $path, className: $className, ignoreComment: $ignoreComment)';
}

/// File header of generated file.
const String rFileHeader =
    '/// GENERATED BY assets_scanner_plus. DO NOT MODIFY BY HAND.\n'
    '/// See more detail on https://github.com/amorenew/assets_scanner_plus.';

/// Ignore for file definition.
const ignoreForFile = '// ignore_for_file: '
    'always_put_control_body_on_new_line,'
    'always_specify_types,'
    'annotate_overrides,'
    'avoid_annotating_with_dynamic,'
    'avoid_as,'
    'avoid_catches_without_on_clauses,'
    'avoid_returning_this,'
    'lines_longer_than_80_chars,'
    'omit_local_variable_types,'
    'prefer_expression_function_bodies,'
    'sort_constructors_first,'
    'test_types_in_equals,'
    'unnecessary_const,'
    'unnecessary_new,'
    'public_member_api_docs,'
    'constant_identifier_names,'
    'prefer_double_quotes';

/// Borrow from https://github.com/dart-lang/sdk/blob/c3f96e863ff402be32aa7acf51ee05b7de0b9841/pkg/analyzer/lib/src/lint/util.dart#L15
final _identifier = RegExp(r'^([(_|$)a-zA-Z]+([_a-zA-Z0-9])*)$');
final _identifierStart = RegExp(r'^([(_|$)a-zA-Z]+)');
final _invalidIdentifierCharacters = RegExp(r'[^_a-zA-Z0-9]+');
const _propertyNamePrefix = 'r_';

/// [AssetsBuilder] will get the assets path from `pubspec.yaml` and generate
/// a `r.dart` with `const` properties of assets path by default. You can custom
/// it by adding an `assets_scanner_plus_options.yaml` file, and the supported key
/// is same with [_AssetsScannerOptions]'s properties name.
class AssetsBuilder extends Builder {
  /// The options for the assets scanner YAML.
  late final _AssetsScannerOptions options = _loadOptions();

  @override
  Map<String, List<String>> get buildExtensions {
    var extensions = 'r.dart';
    if (options.path != 'lib' && options.path.startsWith('lib/')) {
      extensions = '${options.path.replaceFirst('lib/', '')}/$extensions';
    }
    // TODO: It's so wired that this works, but the `buildExtensions` here not
    // match the `build_extensions` in the `build.yaml` file. Need more research see
    // if it's a correct way.
    return {
      r'$lib$': ['$extensions']
    };
  }

  @override
  Future<void> build(BuildStep buildStep) async {
    final pubspecYamlMap = await _loadPubspecYamlMap(buildStep);
    if (pubspecYamlMap?.isEmpty ?? true) return;

    if (!options.path.startsWith('lib')) {
      log.severe(
          'The custom path in assets_scanner_plus_options.yaml should be sub-path of lib/.');
      return;
    }

    final rClass =
        await _generateRFileContent(buildStep, pubspecYamlMap!, options);
    if (rClass.isEmpty) return;

    final dir = options.path.startsWith('lib') ? options.path : 'lib';
    final output = AssetId(buildStep.inputId.package, p.join(dir, 'r.dart'));
    await buildStep.writeAsString(output, rClass);
  }

  Future<String> _generateRFileContent(BuildStep buildStep,
      YamlMap pubspecYamlMap, _AssetsScannerOptions options) async {
    final assetPathsClass =
        await _createRClass(pubspecYamlMap, buildStep, options);
    final packageAssetPathsClass = _createPackageAssetsClass(pubspecYamlMap);

    if (assetPathsClass.isEmpty && packageAssetPathsClass.isEmpty) {
      return '';
    }

    final rFileContent = StringBuffer()
      ..writeln(rFileHeader)
      ..writeln(assetPathsClass);
    if (packageAssetPathsClass.isNotEmpty) {
      rFileContent.writeln(packageAssetPathsClass);
    }

    return rFileContent.toString();
  }

  String _createPropertyName(String assetPath) {
    var propertyName = assetPath.substring(
        assetPath.indexOf('/') + 1, assetPath.lastIndexOf('.'));
    // On iOS it will create a .DS_Store file in assets folder which will
    // cause an empty property name, so we skip it.
    if (propertyName.isEmpty) return propertyName;

    if (_identifier.hasMatch(propertyName)) {
      // Ignore the parent path to make the property name shorter.
      propertyName = propertyName.replaceAll('/', '_');
    } else {
      final shouldAddPrefix = !_identifierStart.hasMatch(propertyName);
      propertyName = propertyName.replaceAllMapped(
        _invalidIdentifierCharacters,
        (match) => '_',
      );
      if (shouldAddPrefix) {
        propertyName = _propertyNamePrefix + propertyName;
      }
    }

    return propertyName;
  }

  Future<String> _createRClass(YamlMap pubspecYamlMap, BuildStep buildStep,
      _AssetsScannerOptions options) async {
    var assetPaths =
        await _findAssetIdPathsFromFlutterAssetsList(buildStep, pubspecYamlMap);

    // remove .DS_Store files which is autogenerated by macOS
    assetPaths = assetPaths
        .where((asset) => !asset.toLowerCase().endsWith('.ds_store'))
        .toList()
      ..sort();

    if (assetPaths.isEmpty) {
      return '';
    }

    final assetPathsClass = StringBuffer()
      ..writeln('class ${options.className} {')
      ..writeln('  static const package = \'${buildStep.inputId.package}\';')
      ..writeln();

    for (final assetPath in assetPaths) {
      final propertyName = _createPropertyName(assetPath);
      if (propertyName.isNotEmpty) {
        if (!options.ignoreComment) {
          assetPathsClass.writeln('  /// ![](${p.absolute(assetPath)})');
        }
        assetPathsClass
          ..writeln('  static const $propertyName = \'$assetPath\';')
          ..writeln();
      }
    }

    assetPathsClass.writeln('  static const allSVGAssets = [');
    final svgs = assetPaths
        .where((assetPath) => assetPath.endsWith('.svg'))
        .toList()
      ..sort();

    for (final assetPath in svgs) {
      final propertyName = _createPropertyName(assetPath);

      if (propertyName.isNotEmpty) {
        assetPathsClass..writeln('    $propertyName,');
      }
    }

    assetPathsClass
      ..writeln('  ];')
      ..writeln()
      ..writeln(ignoreForFile)
      ..writeln('}');

    return assetPathsClass.toString().trim();
  }

  String _createPackageAssetsClass(YamlMap pubspecYamlMap) {
    final assetPaths = _getAssetsListFromPubspec(pubspecYamlMap);
    final packageAssetPaths = <String, Map<String, String>>{};

    for (final assetPath in assetPaths) {
      // Handle the package assets, more detail about the directory structure:
      // https://flutter.dev/docs/development/ui/assets-and-images#bundling-of-package-assets
      if (assetPath.startsWith('packages')) {
        final segments = assetPath.split('/');
        if (segments.length >= 3) {
          final packageName = segments[1];
          final assetPathsOfPackage =
              packageAssetPaths.putIfAbsent(packageName, () => {});
          // The length of `packages/<package-name>/`
          final actualAssetPath = segments.sublist(2).join('/');
          final propertyName = actualAssetPath
              .substring(0, actualAssetPath.lastIndexOf('.'))
              .replaceAll('/', '_');
          assetPathsOfPackage[propertyName] = actualAssetPath;
        }
      }
    }

    if (packageAssetPaths.isEmpty) {
      return '';
    }

    final packageAssetPathsClass = StringBuffer();
    final pubspecDependencies = _getPackagesFromPubspec(pubspecYamlMap);

    packageAssetPaths.forEach((packageName, assetPaths) {
      if (!pubspecDependencies.contains(packageName)) return;

      final className = packageName
          .split('_')
          .map((part) => '${part[0].toUpperCase()}${part.substring(1)}')
          .join('');
      packageAssetPathsClass
        ..writeln('class $className {')
        ..writeln('  static const package = \'$packageName\';');
      assetPaths.forEach((propertyName, assetPath) {
        packageAssetPathsClass
            .writeln('  static const $propertyName = \'$assetPath\';');
      });
      packageAssetPathsClass
        ..writeln(ignoreForFile)
        ..writeln('}');
    });

    return packageAssetPathsClass.toString();
  }

  Future<YamlMap?> _loadPubspecYamlMap(BuildStep buildStep) async {
    final pubspecAssetId = AssetId(buildStep.inputId.package, 'pubspec.yaml');
    final pubspecContent = await buildStep.readAsString(pubspecAssetId);
    return loadYaml(pubspecContent) as YamlMap?;
  }

  Set<String> _getPackagesFromPubspec(YamlMap pubspecYamlMap) {
    final dependencies = pubspecYamlMap['dependencies'] as YamlMap?;
    return dependencies != null ? Set<String>.from(dependencies.keys) : {};
  }

  Set<String> _getAssetsListFromPubspec(YamlMap pubspecYamlMap) {
    final flutterMap = pubspecYamlMap['flutter'] as YamlMap?;
    final assetsList = flutterMap?['assets'] as YamlList?;
    // It's valid that set the same asset path multiple times in pubspec.yaml,
    // so the assets can be duplicate, use `Set` here to filter the same asset path.
    return assetsList != null ? Set<String>.from(assetsList) : {};
  }

  /// Get `assets` value from `pubspec.yaml` file.
  Set<Glob> _createAssetsListGlob(YamlMap pubspecYamlMap) {
    return _getAssetsListFromPubspec(pubspecYamlMap).map((asset) {
      return asset.endsWith('/') ? Glob('$asset*') : Glob(asset);
    }).toSet();
  }

  Future<List<String>> _findAssetIdPathsFromFlutterAssetsList(
      BuildStep buildStep, YamlMap pubspecYamlMap) async {
    final globList = _createAssetsListGlob(pubspecYamlMap);
    final assetsSet = <AssetId>{};

    for (final glob in globList) {
      final assets = await buildStep.findAssets(glob).toList();
      assetsSet.addAll(assets);
    }

    return assetsSet.map((e) => e.path).toList();
  }

  /// Create [_AssetsScannerOptions] from `assets_scanner_plus_options.yaml` file
  _AssetsScannerOptions _loadOptions() {
    final optionsFile = File('assets_scanner_plus_options.yaml');
    if (optionsFile.existsSync()) {
      final optionsContent = optionsFile.readAsStringSync();
      if (optionsContent.isNotEmpty) {
        return _AssetsScannerOptions.fromYamlMap(
            loadYaml(optionsContent) as YamlMap);
      }
    }

    return _AssetsScannerOptions();
  }
}
